---
- hosts: all
  sudo: true
  vars:

    - bamboo_version: "5.6.2"

    - psql_db: bamboo
    - psql_localhost_method: trust

    - docker_users:
        - vagrant
        - bamboo
        - bamboo-agent

    - bamboo_agent_capabilities:
        - ['system.builder.command.docker', '/usr/bin/docker']
        - ['system.builder.command.fig',    '/usr/local/bin/fig']

  roles:
    - ubuntu-common
    - postgres
    - docker
    - bamboo-server
    - bamboo-agent
