---
- hosts: all
  sudo: true
  vars:

    - bamboo_version: "5.8.1"
    
    - psql_db: bamboo
    - psql_localhost_method: trust

    - docker_users:
        - vagrant
        - bamboo
        - bamboo-agent

    - bamboo_agent_capabilities:
        - ['docker.executable', '/usr/bin/docker']
        - ['docker-compose.executable',    '/usr/local/bin/fig']

  roles:
    - ubuntu-common
    - postgres
    - docker
    - bamboo-server
