---
- hosts: all
  sudo: true
  vars:

    - psql_db: stash
    - psql_localhost_method: trust

    # Uncomment these to do full setup
    - stash_license: "YOUR_LICENSE_WITHOUT_NEWLINES"
    - stash_admin_passwd: "A_SECURE_PASSWORD"

  roles:

    - postgres

    # 1st run does full setup in devmode
    - { role: stash, stash_setup: true }
    # 2nd reverts to non-devmode
    - role: stash
