---
- hosts: all
  sudo: true
  vars:

    - bamboo_version: "5.6.2"
    
    - psql_db: stash
    - psql_localhost_method: trust

  roles:
    - ubuntu-common
    - postgres
    - stash
    - ubuntu-systemd
