---

- name: Setup environment
  lineinfile: dest=/etc/environment line="{{item}}"
  with_items:
    - "LANGUAGE=en_US.UTF-8"
    - "LC_ALL=en_US.UTF-8"


- name: Install basic packages
  apt: pkg=python-pycurl state=installed   update_cache=true cache_valid_time=86400

