---

- name: Install Stash dependencies
  apt: pkg=git,curl state=installed

- name: Create base directory
  file: path={{stash_base}} state=directory

- name: Fetch Stash
  get_url: 
    url=http://downloads.atlassian.com/software/stash/downloads/{{stash_tar}}
    dest={{stash_base}}/{{stash_tar}}

- name: Unpack Stash
  command: 
    creates={{stash_dir}}
    chdir={{stash_base}}
    tar xzf {{stash_tar}}


- name: Create user
  user: 
    name={{stash_user}}
    home={{stash_home}}
    createhome=true


- name: Fix permissions for working directories
  file: path={{stash_base}}/{{stash_dir}}/{{item}} owner={{stash_user}} state=directory recurse=true
  with_items:
    - logs
    - temp
    - work


- name: Create config directory
  file: path={{stash_home}}/shared/ state=directory owner={{stash_user}}

- name: Install default config
  template: src="stash-config.properties.j2" dest="{{stash_home}}/shared/stash-config.properties"


- name: Symlink install to current
  command:
    chdir={{stash_base}}
    ln -sf {{stash_dir}} current


- name: Install systemd unit
  template:
    src=stash.service.j2
    dest=/etc/systemd/system/stash.service
  register: svc

- name: Reload and enable service
  shell: 
    systemctl daemon-reload && \
    systemctl enable stash.service && \
    systemctl restart stash.service
  when: svc.changed

- name: Wait for JVM to come up
  wait_for: host=localhost port=7990 delay=2 timeout=120 state=started



- name: Install Stash license
  command: >
     curl -H 'Content-Type: application/json' \
          --data '{"license":"{{stash_license}}" }' \
          --user admin:admin \
          'http://localhost:7990/rest/api/1.0/admin/license'
  when: stash_setup


- name: Create Admin user
  command: >
     curl -H 'Content-Type: application/json' --data '' \
          --user admin:admin \
          'http://localhost:7990/rest/api/1.0/admin/users?name={{stash_admin_user}}&password={{stash_admin_passwd}}&displayName=AdminUser&emailAddress=root@localhost'
  when: stash_setup

- name: Set Admin user permissions
  command: >
     curl -H 'Content-Type: application/json' --data '' \
          --user admin:admin \
          --request PUT \
          'http://localhost:7990/rest/api/1.0/admin/permissions/users?permission=SYS_ADMIN&name={{stash_admin_user}}'
  when: stash_setup
