---

- name: Install Postgres
  apt: pkg=postgresql-{{psql_version}} state=installed

- name: Configure DB access
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{psql_version}}/main/pg_hba.conf
  notify: restart_psql

- name: Create database user
  sudo_user: postgres
  command: createuser {{psql_db}}
  ignore_errors: true
  when: psql_db is defined

- name: Create database
  sudo_user: postgres
  command: createdb {{psql_db}} -O {{psql_db}}
  ignore_errors: true
  when: psql_db is defined
